-- DDL de ejemplo: Sistema de Gestión de Requerimientos Internos (laboratorio)
-- Ejecutar en el esquema acordado (p. ej. REQ_DEV). Ajustar tablespaces según política DBA.
-- No contiene datos personales reales.

CREATE TABLE req_requerimiento (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo          VARCHAR2(500) NOT NULL,
  descripcion     CLOB,
  solicitante     VARCHAR2(200),
  area            VARCHAR2(200),
  prioridad       VARCHAR2(20) DEFAULT 'media',
  estado          VARCHAR2(40) DEFAULT 'borrador',
  glpi_ticket_id  VARCHAR2(50),
  creado_en       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  actualizado_en  TIMESTAMP
);

CREATE TABLE req_comentario (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requerimiento_id NUMBER NOT NULL REFERENCES req_requerimiento (id),
  autor            VARCHAR2(200),
  texto            CLOB NOT NULL,
  creado_en        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_req_estado ON req_requerimiento (estado);
CREATE INDEX idx_req_glpi ON req_requerimiento (glpi_ticket_id);
